### ISSUE TITLE
Unable to File issues to Azure Boards from Insights for Web - FastPass

### ISSUE THREAD

**Issue by TechnopriseC** [microsoft/accessibility-insights-web#1009]
## Describe the bug

Unable to File issues to Azure Boards from Insights for Web - [FastPass] when you select the 'File issues' button in the Failure details section.

**To Reproduce**

1. Open the desired website to test
2. Click on the Chrome extension for Accessibility Insights for Web
3. Select FastPass
4. Run the Automated Checks on the site; Show failures = On
5. Click on the 'gear' and go to settings
6. Make sure the desired Azure Boards project link is setup in the settings
7. File issue details in: Description
8. For the reported Failure, select/click the "File issue" button
9. Observe the page throws a error - "Server error typeNames"
10. The URL is correct - https://dev.azure.com/org/project/_workitems/create/Bug?...
11. The word 'Bug" is incorrect and should be "Issue" [e.g. /_workitems/create/Issue?

## Expected behavior

When you make this change in the URL, the Work Item is successfully created in Azure DevOps >Work items
   Corrected URL - https://dev.azure.com/org/project/_workitems/create/Issue?...

## Screenshots

Attached

## Extension (please complete the following information)

- OS: Windows
- Version 10.0.18362
- Browser Version : Chrome Version 76.0.3809.87

## Did you search for similar existing issues? 
Yes

## Additional context

![Server Error_typeNames_1](https://user-images.githubusercontent.com/53736772/62444192-d285bc00-b72a-11e9-94a8-b2ffe6771278.PNG)
![Server Error_typeNames_URL_Bug](https://user-images.githubusercontent.com/53736772/62444198-d6194300-b72a-11e9-8485-01581042fcaf.PNG)

**Comment by ferBonnin** [comment]
Thanks for reporting this @TechnopriseC!

Shobhit and I talked about this. It indeed looks like something recently changed and now the URL needs to say **Issues** for bugs filed in _Description_.

While we look into this, there is a workaround to manually change the url from bug to issue:
htttps://dev.azure.com/org/project/_workitems/create/Bug?...
Change to
htttps://dev.azure.com/org/project/_workitems/create/Issue?...

**Comment by ferBonnin** [comment]
Per investigation, we can assume that if the user selects _repro steps_ then its a bug and if they select _description_ then it is an issue. This can be addressed by changing the url if the user selects _description_

**Comment by karanbirsingh** [comment]
Some various cases:
- if Azure Boards is not enabled at all, user gets a 404 ([example](https://dev.azure.com/ms/accessibility-insights-web/_workitems))
- if bugs or issues are not enabled due to process type, user gets server error 
- default processes always show the same layout (repro steps for bugs, description for issues). Users can customize these ([example](https://dev.azure.com/karansin/scrum-fancy-bugs/_workitems/create/Bug))

Two scenarios where our proposed solution may be confusing:
- User uses default scrum (bugs, no issues) but for some reason wants to use description in history instead of repro steps for this - we change to issue instead and user gets server error
- User has customized heavily (like scrum-fancy-bugs) - we change to issue instead and user gets server error

We don't think these are two common & will make this simple change for now

**Comment by karanbirsingh** [comment]
@TechnopriseC @ferBonnin We've pushed a potential fix in our Canary extension [here](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem). Feel free to try it and let us know if things look good. Thanks!
