### ISSUE TITLE
Failure panel push down when expanding a failure group

### ISSUE THREAD

**Issue by smoralesd** [microsoft/accessibility-insights-web#1289]
## Describe the bug

Failure panel disappear and double scroll bar shows up if the window is "small enough" and the user expand a failure group with "enough" instances.

**To Reproduce**

1. Navigate to http://www.washington.edu/accesscomputing/AU/before.html
1. Open details view -> fast panel -> automated checks
1. Wait for the failure list to be loaded
1. Make sure the details view windows is "small enough" 
1. Expand the "label" group
1. Observe: the failure details panel gets push down and disappear from the view; also there are 2 vertical scroll bars present, one on the failures list and one on the external container

## CodePen repro example

Does not apply

## Expected behavior

At least, no double scroll bar.
We probably want to better control the size and position of the Failure details panel

## Screenshots

![01 - failure details panel](https://user-images.githubusercontent.com/2837582/65552693-e7383200-ded9-11e9-96b3-59989ccdd566.gif)

## Extension (please complete the following information)

- OS: Windows 10
- Version 2.10.0 insider
- Browser Version: Microsoft Edge dev Version 79.0.279.0 (Official build, 64-bit)
 & Chrome 76.0.3890.132 (Official Build, 64-bit)
- Target Page http://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

No

**Comment by smoralesd** [comment]
#1118 may be related

**Comment by waabid** [comment]
This might be due to a browser update. This is what I saw on Edge 78.x:

![scrollbug_nonrepro_edge78](https://user-images.githubusercontent.com/32555133/65628050-85350680-df85-11e9-80ff-93853066940d.gif)

**Comment by ferBonnin** [comment]
@smoralesd could you verify this is fixed in Edge  and Chrome 78.x ? If it isnt, please mark as ready for work

**Comment by dbjorge** [comment]
Verified in chrome 77 (stable) and 79 (dev). Closely related to #1118; will be considering their fixes in tandem.

**Comment by dbjorge** [comment]
@ferBonnin / @cheade , can you help me understand exactly what behavior you'd actually like to see here?

We don't currently enforce a minimum allowed viewport height, and both the instance table and the failure details pane have variable height content that could *each individually* be taller than what I'd consider to be a "reasonable" viewport height (especially at 200% font size). Given these constraints, the only option that comes to mind as avoiding double scrollbars is to give the entire content pane a single scrollbar (ie, the failure panel would not "stick" to the bottom).

I have a fix in development for #1118 that incidentally implements that behavior (the single-scrollbar). I'm not super inclined to spend tons of time on this since we're planning to replace the whole table with cards soon anyway. Does this sound reasonable, or is the stickiness of the failure panel more of a necessity than avoiding the double-scrollbars?

**Comment by ferBonnin** [comment]
@dbjorge could you send a gif on how the solution you propose would look like?

**Comment by dbjorge** [comment]
![gif of proposed scrollbar behavior](https://user-images.githubusercontent.com/376284/65986366-90ca7680-e438-11e9-8355-ea444cdb6ce5.gif)

**Comment by ferBonnin** [comment]
per conversation with Peter, this fix is temporally ok (until we replace this whole UI) and a better experience than what we currently we have with this bug

**Comment by ferBonnin** [comment]
before the PR, lets check this doesn't affect keyboard-only nav.
A small note is that this could potentially affect discoverability of the details panel.

**Comment by dbjorge** [comment]
I don't think it's changed keyboard-only nav; in testing with NVDA, tabbing to the table, navigating the table, escaping the table, and continuing downing/tabbing still proceeds to the failure details pane as normal.

I agree that this could affect discoverability of the details panel for cases with many types of failure; if we weren't replacing this whole UI in the immediate future anyway, I think it would make sense to give more thought to avoiding that :)

**Comment by ferBonnin** [comment]
thanks for checking Dan :) 
we are fine with the discoverability since, as you mention, we are planning to change this UI

**Comment by dbjorge** [comment]
Resolved by #1334
