### ISSUE TITLE
<li> elements must be contained in a <ul> or <ol>

### ISSUE THREAD

**Issue by vikasgupta18** [microsoft/accessibility-insights-web#1575]
## Describe the bug

**To Reproduce**

1. Go to answers.microsoft.com
2. Click on Participate and run accessibility insight tool, It is complaining about "<li> elements must be contained in a <ul> or <ol>"

I verified the html for this and I confirm that <li> elements are already inside <ul>

Here is the code snippet for the same : 
![image](https://user-images.githubusercontent.com/14251420/67810876-b6a76300-fa58-11e9-889f-7f01a550419b.png) 

## Expected behavior

As it is configured as expected it should not show error for fast pass. 

## Screenshots

![image](https://user-images.githubusercontent.com/14251420/67810975-ea828880-fa58-11e9-80c4-10264996eabc.png)

## Extension (please complete the following information)

- OS: Windows 10 enterprise
- Version : 10.0.18362
- Browser Version Chrome 71.0]
- Target Page www.answers.microsoft.com

## Are you willing to submit a PR?

Yes

**Comment by iamrafan** [comment]
hi @vikasgupta18, the issue you see is a failure in the sub-list rather than the list you mentioned in the code snippet. Please find the correct snippet from below

![image](https://user-images.githubusercontent.com/22068434/67812272-020f4080-fa5c-11e9-8513-8f0526cebe64.png)
 

This is a valid issue and as highlighted above it is caused by the empty ```<li>``` items which do not have ```role presentation``` and are interpreted as parent-less ```listitem```s by the accessibility tree

**Comment by vikasgupta18** [comment]
Thanks for your reply. This was helpful.
