### ISSUE TITLE
No pop-up dialog when uninstalling and installing again Electron

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#1868]
## Describe the bug

When uninstalling and installing again the electron app, I don't get the telemetry pop-up dialog again

## Expected behavior
always get the initial pop-up dialog on installation

**Comment by karanbirsingh** [comment]
This occurs because the AI-Android data in indexeddb persists between installations. This data is stored in `C:\Users\--username--\AppData\Roaming\Accessibility Insights for Android\IndexedDB\`

In the Chrome extension, AI-Web indexeddb data is removed when the extension is removed.

Some options to explore might include:
- Write a [custom NSIS uninstaller](https://www.electron.build/configuration/nsis#custom-nsis-script) script to clear the folder upon uninstall
- Persist the version number alongside indexeddb data and write application code on startup that resets required preferences (need to understand how much is shared between web + android flow here)

**Comment by ferBonnin** [comment]
will address as part of feature

**Comment by ferBonnin** [comment]
looks good! this fix introduced a new issue with the final screen. Created #1974
