### ISSUE TITLE
Automated checks visual helper behaves differently in ad hoc and assessment page

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#1932]
## Describe the bug

The visual helper for automated checks behaves slightly differently when turned on from the assessment page vs when turned on from the ad hoc tools panel (when turned on from the assessment page, I can't click the [!] box on the target page to see issue details). This is by design, but because both visual helpers look identical, I expected them to work the same and thought that something was wrong when they didn't.

**To Reproduce**

1. Turn on visual helper from ad hoc tools
2. Click any [!] box to open issue details
3. Turn off visual helper from ad hoc tools
4. Open assessment page and turn on visual helper for automated checks
5. Try to click the [!] box and see that issue details does not appear

## Expected behavior

Both visual helpers either have the same behavior or appear different to avoid the assumption that they behave identically.

## Context (please complete the following information)

- OS Name & Version: Windows 10.0
- AI-Web Version & Environment: Insider 2.13.0
- Browser Version: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Target Page: https://www.bing.com

**Comment by ferBonnin** [comment]
Per conversation with Peter, by design. the scenario to use automated checks in assessment is different than in FastPass and thus, users are not expected to click in each one of the failures (ideally, these issues are fixed before starting an assessment since they are low hanging fruit). Also, if this happened for automated checks in assessment would users be confused that other tests don't do this?

**Comment by smoralesd** [comment]
Did we consider the option of making the highlighting different on each case? We could keep the exclamation mark on the case of fast pass and use a different character on the case of assessment.

**Comment by lisli1** [comment]
I think @pownkel and @smoralesd bring up a good point. I was also confused when I first used the tool because the highlight boxes look exactly the same in both FastPass and Assessment but behave differently, when one would expect them to behave the same. Do we know if people generally use FastPass and fix all the automated checks issues before doing the Assessment, or if they prefer to do everything in Assessment (including automated checks)?

**Comment by ferBonnin** [comment]
> Did we consider the option of making the highlighting different on each case? We could keep the exclamation mark on the case of fast pass and use a different character on the case of assessment.
Yes, but then the issue is consistency between the different parts of the tool and our other tools. 
Thus, what we did was change the mouse from a pointer to a hand to show that the elements are clickable.

> Do we know if people generally use FastPass and fix all the automated checks issues before doing the Assessment, or if they prefer to do everything in Assessment (including automated checks)?
Yes, based on user interviews, FastPass is used (and recommended) for every UI change and an Assessment is only done when the feature is completed.

This hasn't come up before from user interviews or questions, but we now have this issue and we will monitor for upvotes or comments from users and revisit if needed.
