### ISSUE TITLE
Some headings not visualized when target page changed

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-web#2325]
## Describe the bug

When scanning a local html file, if we change the target page while the headings visualizer is on, the visualizer remains on and starts highlighting headings in the new target page. However, only some headings are highlighted. Note that this happens whether or not iframes permissions are granted.

**To Reproduce**

1. Open a local html file in chrome (for example, [this test file](https://github.com/microsoft/accessibility-insights-web/blob/master/src/tests/end-to-end/test-resources/native-widgets/input-type-radio.html))
2. Start a new assessment
3. Turn on the headings visual helper
4. In the target page, navigate to a different local html file (for example, [this other test file](https://github.com/microsoft/accessibility-insights-web/blob/master/src/tests/end-to-end/test-resources/all.html))
5. Click "continue previous"
5. Note that some headings are still visualized in the new target page (screenshot example below)
6. Start the assessment over
7. Turn the headings visualizer back on
8. Note that more headings are now visualized than previously (screenshot example below)

## Expected behavior

The headings visualizer visualizes all headings on the new target page.

## Screenshots

Here is an example target page with headings visualized immediately after navigating to a new file:

<img width="1126" alt="headers1" src="https://user-images.githubusercontent.com/55459788/76259656-59e06400-6213-11ea-9de1-e8cd952f2e11.PNG">

And the same page with the headings visualized after restarting the assessment:

<img width="1128" alt="headings2" src="https://user-images.githubusercontent.com/55459788/76259697-6e246100-6213-11ea-964d-262f56cf1f6d.PNG">

## Context (please complete the following information)

- OS Name & Version: Windows 10 version 1909 Build 18363.657
- AI-Web Version & Environment: Insider 2.15.0
- Browser Version: 80.0.3987.122 (Official Build) (64-bit)
- Target Page: www.bing.com

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by waabid** [comment]
This is expected behavior.

What you're seeing here is the app trying to visualize based off the data found in the previous scan on the first website. In most situations, there would be very few items that are visualized because of course different websites will have different selectors generated for the elements. In this case, these websites seem to share a lot of the selectors so the app looks like it "almost works" but doesn't.

The "continue previous" feature is targeted towards users coming back to finish an assessment on a website they were previously testing, where the visualizations would be correct. So while this may cause some confusion, it is not a user behavior we would see often and hence, are leaving it as is.
