### ISSUE TITLE
Accessibility Insights popup is not showing up 

### ISSUE THREAD

**Issue by kar183** [microsoft/accessibility-insights-web#2460]
## Describe the bug
Accessibility Insights popup is not showing up. We guess the code on the git hub repository is not upto date

**To Reproduce**

1. Downloaded the git hub file from here and loaded the unpacked version to chrome.
2. Go to google.com
3. Click on accessibility insights icon 

## Expected behavior

Once we click on Accessibility Insights icon we should see the Accessibility Insights popup with the  fast pass option

## Screenshots

![image](https://user-images.githubusercontent.com/28563498/78630321-0bc48c00-78b7-11ea-8f2c-97c4919faa99.png)

## Context (please complete the following information)

- OS Name & Version:  Windows 10.0.18363 Build 1909
- Browser Version: 80.0.3987.149 (Official Build) (64-bit))
- Target Page:  https://www.google.com

## Are you willing to submit a PR?
No

## Did you search for similar existing issues?
No

## Additional context
No other context

**Comment by ferBonnin** [comment]
Hi @kar183 thanks for reporting this issue!

To help us understand and reproduce the issue, can you help us with the following information?

1. from step 1 in the repro steps, from where are you getting the extension file?
1. from step 1, sounds like like you are unpackaging and installing, is this correct?
1. can you please go to chrome://extensions/ and share the version of the extension?
1. would you be willing to send us any console output from the background and popup?
1. can you try installing directly from the [Chrome store](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni) to check if that unblocks you?
2. does [canary ](https://chrome.google.com/webstore/detail/hbcplehnakffdldhldncjlnbpfgogbem)and [insider ](https://chrome.google.com/webstore/detail/nnmjfbmebeckhpejobgjjjnchlljiagp)work for you?

**Comment by ferBonnin** [comment]
Hi @kar183 Thanks for reaching out! 

Based on the repro steps and screenshot you provided, we think you're trying to install Accessibility Insights for Web by downloading the "Source code" zip file from our GitHub Releases page and asking Chrome to load some folder inside it as an unpacked extension.
This is not a supported means of installing Accessibility Insights for Web; the Source code zip files only contain source code, and do not contain built/working versions of the product.
To install Accessibility Insights for Web, you should [download it from the Chrome Web Store](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni). If you are interested in building from source, see [Building Accessibility Insights for Web](https://github.com/microsoft/accessibility-insights-web/blob/master/docs/building-web.md).

**Comment by kar183** [comment]
Hello Team,

Thanks  for the quick response. Please find the answers inli

   1. We are getting the extension files from here.
   2. Yes
   3. Current version: 1.0.4
   4. There is no output currently
   5. This doesn't fit for our use case
   6. No


We have want to know why there is a discrepancy  between source cod and
working version

Thanks
Karthik

**Comment by kar183** [comment]
karthik kohli <karthikminupala183@gmail.com>
19:18 (23 minutes ago)
to *microsoft/accessibility-insights-web*, *Mention*,
microsoft/accessibility-insights-web
Hello Team,

Thanks  for the quick response. Please find the answers inline below

   1. We are getting the extension files from here
   <https://github.com/microsoft/accessibility-insights-web>.
   2. Yes
   3. Current version: 1.0.4
   4. Screenshot of Background.html output console
   [image: image.png]
   5. This doesn't fit for our use case, Where can we find the source code
   of existing version 2.16.0
   6. No


We  also want to know why there is a discrepancy  between source code
available on the github
<https://github.com/microsoft/accessibility-insights-web>and Published
version which is on the Chrome store
<https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni>

Thanks
Karthik

**Comment by lisli1** [comment]
Hi @kar183, we are unable to view the image you attached in your email response. Could you post it by using the GitHub client instead?

There is a discrepancy between the published extension and the source code because we modify the version as a part of our release and it is not updated in the source code every time we release. 

Based on the repro steps you provided, it seems that you downloaded the zip file from the [release for 2.16.0](https://github.com/microsoft/accessibility-insights-web/releases/tag/web%402.16.0), and then loaded the unpacked version into Chrome. However, the zip is simply a snapshot of the repo at the time of release, and you would still need to **build** it by following [these steps](https://github.com/microsoft/accessibility-insights-web/blob/master/docs/building-web.md) to get it working locally. Please let us know if this works for you.

We might be able to provide better assistance if we can understand the use case you are considering by building from source. Would you mind sharing more info on this?

**Comment by kar183** [comment]
Hello Team,

We have downloaded the extension from [here](https://github.com/microsoft/accessibility-insights-web/releases/tag/web%402.16.0) version 2.16.0 and when we unpack and load it to chrome or just see the maifest.json file we are seeing the version as 1.0.4 and not 2.16.0. we are not sure what's wrong here.
![image](https://user-images.githubusercontent.com/28563498/78871404-44a26380-7a65-11ea-8cc7-a4c49d105207.png)
![image](https://user-images.githubusercontent.com/28563498/78871534-79161f80-7a65-11ea-97eb-55268ae658b8.png)

We are more  aligned towards making changes into the code as per our use case rather building it locally yarn. We want to unpack the customized extension code onto the chrome. Can you please guide us towards the same.

**Comment by lisli1** [comment]
To clarify the version number discrepancy, this zip folder is essentially a snapshot of what the repo contained at the time of release. Even though it says v1.0.4, it **does** have all the updates/changes that you would see in the extension found in the Chrome store for v2.16.0. The reason why the version number you see when you downloaded the extension from the GitHub release (1.0.4) doesn't match the actual version (2.16.0) is because we don't update the version in the repo when we release; the version number gets updated as part of our release process, so it shows 2.16.0 in the Chrome store but always stays the same in the repo (1.0.4). 

**Do not worry that the version numbers don't match; as long as you download the source code from the [2.16.0 release](https://github.com/microsoft/accessibility-insights-web/releases/tag/web%402.16.0), you will have all the code changes that we added for this release.**

It looks like you downloaded the zipped source code from the 2.16.0 release, so you are on the right track there. You can make the changes that you want and unpack the customized extension into Chrome:

1. First and foremost, **you must build the extension locally for it to run right away. If you skip this step, the extension will not run.** Please [follow these instructions to build](https://github.com/microsoft/accessibility-insights-web/blob/master/docs/building-web.md) and get your extension working locally.
2. Make any changes you want to the code.
3. Build after you make the changes, so that the built extension has all the changes you made.
4. After you are satisfied with the modifications **and have built the project after making the changes**, you can unpack the extension into Chrome and share the modified, built package with your team, so they can also unpack the extension into Chrome.
