### ISSUE TITLE
Text changes to Sequence > Columns and Semantics > Table semantics

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-web#2610]
## Describe the bug

See attached file for text changes to two requirements:

- **Sequence** > **Columns**
- **Semantics** > **Table semantics**

[Updates to Sequence and Semantics.docx](https://github.com/microsoft/accessibility-insights-web/files/4576191/Updates.to.Sequence.and.Semantics.docx)

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

**Comment by ferBonnin** [comment]
Reviewed with Peter, looks good

**Comment by dbjorge** [comment]
Making the updates now. @LiLoDavis / @ferBonnin , the document suggests adding additional guidance on columns with a link like [CSS Multi-column Layout Module Level 1](https://www.w3.org/TR/css-multicol-1/); I noticed that MDN has a pretty good introductory documentation page for [Multiple-column layout](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Multiple-column_Layout) that looks like it would be more useful to a developer, thoughts on using it instead of or in addition to the spec link? (we don't use MDN docs as often as w3 stuff, but we've used it before in the Text Legibility guidance and the Orientation requirement's content).

**Comment by LiLoDavis** [comment]
> thoughts on using it instead of or in addition to the spec link?

If Fer is OK with linking to MDN, I recommend including both.

**Comment by dbjorge** [comment]
All set! Canary is updated (with both links) and ready to validate

**Comment by LiLoDavis** [comment]
Looks good.
