### ISSUE TITLE
Clear visualization and show a message to use "Start over" button when using Fastpass link more than once

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-web#3258]
## Describe the bug

On clicking FastPass in Launch Pad we trigger a scan and show the details view page, if the FastPass link is used once again on the same page we do not re scan but we clear the results in details view and keep showing the same visualization in the target page. This creates a false sense that the page was re scanned. 

This is confusing especially in cases where changes are made to the DOM to fix an issue and FastPass link is used, as the target page visualization will keep highlighting the same amount of failures seen before DOM changes

To avoid misleading the users we need to clear the visualization in the target page and show a message in the details view asking the user to use "Start over" button to trigger a re scan. 

**To Reproduce**

1. Go to 'https://www.washington.edu/accesscomputing/AU/before.html'
2. Click on 'FastPass' in launch pad
3. Make changes to in the DOM of the target page to fix one of the issues
4. Use the 'FastPass' link in launch pad once again
5. Observe that the same number of failure are highlighted in the target page despite one issue being fixed
6. Also observe that there is no indication in the details view asking to use the 'Start Over' button to trigger a re scan

## Expected behavior

- Clear visualization in the target page when using 'FastPass' link more than once
- Show a message in details view asking to use 'Start Over' button to trigger a re scan

#### GIF showing the same number of issues highlighted even after one of them being fixed in the DOM
![FastPass link issue-1 1](https://user-images.githubusercontent.com/22068434/90693302-6be71980-e22b-11ea-83ab-21bcf04a839b.gif)

## Context
- OS Name: Windows 10, Version: 1903, Build 18362.476
- AI-Web Version & Environment: Production 2.20.0 
- Browser Version: Google Chrome 84.0.4147.135
- Target Page: https://www.washington.edu/accesscomputing/AU/before.html

**Comment by waabid** [comment]
I'm not sure if I agree with the expected behavior on this one. Previously, before this was broken, what would happen is that we would just show the details view again (and not re-scan). Is there a reason we want to change that expected behavior?

As in to say: the expected behavior should be that the details view instances don't disappear (which is the actual bug here).

**Comment by ferBonnin** [comment]
> before this was broken, what would happen is that we would just show the details view again (and not re-scan)

with the old results or with no results?

> As in to say: the expected behavior should be that the details view instances don't disappear (which is the actual bug here) or so it was, until this bug was introduced.

can you clarify this sentence? not sure if I follow

**Comment by waabid** [comment]
![fastpassclicktwicePRE](https://user-images.githubusercontent.com/32555133/93922912-7764af00-fcc7-11ea-9e15-25aa1f1446e2.gif)

Here is the behavior we had before this bug went in (around the time Needs Review went in). As you can see, if we already have automated checks enabled, we do not re-scan. The behavior described in the bug's expected outcome/the comment above is notably different from this.

Upon further thinking, the question that matters is: do we want to revert to the behavior above or do we want to do something else (like your comment suggests)?

**Comment by ferBonnin** [comment]
Got it, thanks @waabid! I am marking this as needs triage to continue the conversation. The previous behaviour doesn't match the expectations but it does keep the same data in both the visualization and the details view which is slightly better than showing two different things (visualization but clean details view).

To summarize:

* before needs review feature: both the visualization and the automated checks details view stayed the same  (no rescan)
* after needs review feature: the visualization stays and automated checks details view is now shown empty, but without a message to start over. (visualization stay, details view clean)


Expected behaviour:
* If a user is fixing something, the expectation is that running opening FastPass > automated checks from the pop-up menu, re-reruns the checks

Another option:
* clean the visualization and show the message about the Start over button.

**Comment by waabid** [comment]
Sounds good!
 
> * [...] the expectation is that running opening FastPass > automated checks from the pop-up menu, re-reruns the checks

For what it's worth, if we do want to re-scan every time fast pass is pressed, it should be fairly easy to do.

**Comment by ferBonnin** [comment]
reviewed this with Peter again. Makes sense to re-scan every time fastpass is selected.

**Comment by iamrafan** [comment]
As discussed with @ferBonnin, the following issue also needs to be fixed:
- Open a sample target page and go to AI Web ad hoc tools
- Turn on the automated checks toggle
- Click the ```List view and filtering``` link below it	
- Observe that the details view is blank without any results

![MicrosoftTeams-image](https://user-images.githubusercontent.com/22068434/95180076-53e53e00-0776-11eb-917a-b8d4b147aa43.png)

**Comment by ferBonnin** [comment]
verified in canary 2021.11.1.1620
