### ISSUE TITLE
Details dialog not rendering Fix the following on some pages

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-web#3431]
## Describe the bug

**To Reproduce**

1. Go to https://flow.microsoft.com/en-us/
2. Run Automated Checks
3. Click on a failure instance on the target page
4. Observe that fix the following renders an empty bullet list

## Expected behavior
Fix the following displays text

## Screenshots

![image](https://user-images.githubusercontent.com/4615491/94960211-58280780-04a7-11eb-990f-9554f62d1425.png)

## Context (please complete the following information)

- OS Name & Version: Windows 10 version 2004 19041.508
- AI-Web Version & Environment: 2.21.1 prod
- Browser Version: Edge 85.0.564.68
- Target Page: 

## Did you search for similar existing issues?
Yes

## Additional context
Removing `aria-hidden="true"` from the `<span>` containing the how to fix text causes it to display.

**Comment by ferBonnin** [comment]
Per conversation with Peter, looks like this particular page has a CSS rule that if it has aria-hidden = true, then it doesn't display the element. The color boxes are hidden on purpose so the screen reader doesn't read them (since we already add the HEX as part of the text).

Given that this particular page is doing something odd, we are marking this as out of scope.
