### ISSUE TITLE
Command line execution to add this check to a DevOps pipeline

### ISSUE THREAD

**Issue by ricardoserradas** [Microsoft/accessibility-insights-web#359]
## Is your feature request related to a problem? Please describe.
No

## Describe the desired outcome
If possible, it would bring a great impact if we could run this check on a CI/CD pipeline for a Windows/Web application, if possible.

## Describe alternatives you've considered
So far, I don't see any alternatives for achieving this during a DevOps pipeline.

## Additional context
Adding this inclusive concern to the DevOps story would bring such great impact to everyone in the world. I'd be happy to contribute if you need a hand.

**Comment by smoralesd** [comment]
Hi @ricardoserradas 
Thanks for your interest on Accessibility Insights for Web.
We use [axe-core](https://github.com/dequelabs/axe-core) as our scan engine to find accessibility issues on web pages. You can use [axe-cli](https://github.com/dequelabs/axe-cli) in order to run axe from the command line.
