### ISSUE TITLE
Headings are not recognized

### ISSUE THREAD

**Issue by anthonyFer** [microsoft/accessibility-insights-web#3879]
Issue Description:
I cannot find headings using MS insights for Web.

To Reproduce:
1. Go to https://staging.pearsonvue.com/About.aspx
2. Click on MS Insights Ad-hoc Tools
3. Check Headings
4. I don't see headings on the page are highlighted. 
For example "Driving global change, one exam at a time" is marked as a level 2 heading, but it's not flagged as a heading.

- OS Name & Version: Windows 10 Enterprise
- Browser Version:  Chrome Version 88.0.4324.104

**Comment by peterdur** [comment]
It looks like headings in the footer of this page are found, but headings inside the [obsolete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content) `<content>` element are missed. When the `<content>` element is replaced with a `<div>` the contained headings are recognized and highlighted.

**Comment by pownkel** [comment]
Hi @anthonyFer, Since the `<content>` element is deprecated as @peterdur noted, it is no longer supported in Firefox, Chrome, IE, or Safari. The headers should be recognized if `<content>` is replaced with a supported element, like `<div>` or the recommended `<slot>`. Let us know if you have any additional questions!
