### ISSUE TITLE
Duplicate id's within display:none should be ignored

### ISSUE THREAD

**Issue by tohmjudson-ms** [microsoft/accessibility-insights-web#4052]
## Describe the bug

We are currently seeing duplicate id bug errors in HMTL wrapped in display:none

**To Reproduce**

1. Go to https://powerapps.microsoft.com/en-us/signup/
2. Run Accessibility insights for Web
3. In Dev tools: search for class="modal-wrapper-mask", which has the display: none property

## CodePen repro example

https://codepen.io/tohmjudson/pen/rNjBRqY

## Expected behavior

id's within a display:none should be ignored

## Screenshots

![image](https://user-images.githubusercontent.com/35084583/112026728-bb5c3380-8af3-11eb-8b35-2bdd633e80eb.png)

## Context (please complete the following information)

- OS Name & Version: Windows Version  10.0.19042 Build 19042
- AI-Web Version & Environment: Version 2.24.0
- Browser Version:  Google Chrome Version 89.0.4389.90 (Official Build) (32-bit) Microsoft Edge
Version 89.0.774.57 (Official build) (64-bit)
- Target Page: https://powerapps.microsoft.com/en-us/signup/

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by DaveTryon** [comment]
Hi, @tohmjudson-ms! The **duplicate-id** and **duplicate-id-active** errors are going off because the current axe-core rules (the rules at the heart of Accessibility Insights for Web) require the id's to be unique within the entire scope of the HTML document and intentionally ignore the _display:none_ or _visibility:hidden_ attributes. The axe-core team [debated this question](https://github.com/dequelabs/axe-core/issues/862) and ultimately concluded that programmatic access to id's should be independent of display states. In practice, since you're probably using a shared component in the different display states, you just need to specify some sort of property that allows each instance of the shared component to create a context-specific automation id.

All that said, there's a separate [axe-core conversation](https://github.com/dequelabs/axe-core/issues/2808) that could possibly reclassify these rules as best practices. If that happens, Accessibility Insights for Web would eventually move to the updated axe-core and would inherit the same behavior. Since we currently have neither a guarantee of this change or a timetable for incorporating it into Accessibility Insights, it's probably best to add the ability to make the automation id's distinct across the entire HTML document.

I'm marking this as resolved; please close it out at your convenience. Thanks!

**Comment by joelkseattle** [comment]
hey Dave,
this is contrary to the documentation provided by Accessbility Insights however, have you discussed with the AI team?
https://accessibilityinsights.io/docs/en/web/reference/faq/#can-automated-checks-in-accessibility-insights-for-web-detect-issues-in-content-thats-currently-hidden

*_*_from the FAQ__**
_Can automated checks in Accessibility Insights for Web detect issues in content that's currently hidden?
The automated checks run only on visible content; content marked with display: none or visibility: hidden is ignored. To test content that's hidden by default – such as combo box options, dialog boxes, and menu options – you'll need to reveal the content before running automated checks:

Use your mouse or keyboard to reveal the hidden content.
Run the automated checks._

**Comment by DaveTryon** [comment]
Thanks, @joelkseattle! Most rules run only on visible content; the duplicate-id and duplicate-id-active rules are exceptions that should be documented in the FAQ. I've opened https://github.com/microsoft/accessibility-insights-docs/issues/553 to track this change (the repo is private so you'll just have to trust me when I say it's there).
