### ISSUE TITLE
[Windows HC] More actions menu icon is not visible when selected

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#4616]
## Describe the bug

1. When the "more actions" menu icon is selected, the icon is no longer visible. 
2. Similarly, when the menu items are hovered, there does not seem to be sufficient contrast.

* In Windows High Contrast 1, (1) is present.
* In Windows High Contrast 2, (1) is present.
* In Windows High Contrast Black, (1) and (2) are present. For (2), the text of the menu items has insufficient contrast.
* In Windows High Contrast White, (2) is present. The icons of the menu items have insufficient contrast.

**To Reproduce**

1. Turn on Windows HC mode (not from within AI-Web)
2. Run automated checks
3. Open the cards view
4. Select the "more actions" menu on the footer of a card
5. Hover the resulting menu items

## Expected behavior

In all Windows high contrast themes, the (1) menu icon and (2) menu items should still be visible and have sufficient contrast when selected/hovered.

## Screenshots

* AI Web high contrast (**not** Windows high contrast) shows menu icon and menu items visible, with sufficient contrast:
![image](https://user-images.githubusercontent.com/48259897/130871142-d768c7a3-9777-463e-ae92-021e130a9100.png)

* Windows High Contrast 1 shows menu icon not visible:
![image](https://user-images.githubusercontent.com/48259897/130871697-de191c66-1b96-4446-8d28-69d113365e33.png)

* Windows High Contrast 2 shows menu icon not visible:
![image](https://user-images.githubusercontent.com/48259897/130871699-b72a5546-97e8-4274-8cbb-f913c7c80997.png)

* Windows High Contrast Black shows menu icon not visible and text of menu items with insufficient contrast:
![image](https://user-images.githubusercontent.com/48259897/130870325-a1b6af37-b4ea-4c87-9727-8d28cf702827.png)

* Windows High Contrast White shows icon of menu items with insufficient contrast:
![image](https://user-images.githubusercontent.com/48259897/130871688-52f21ae1-7c70-4f38-a517-8acdd52d5275.png)

## Context (please complete the following information)

- OS Name & Version:  Windows Version 10.0.19043 Build 19043
- AI-Web Version & Environment:  2.28.0 Insider
- Browser Version:  Edge Version 92.0.902.62 (Official build) (64-bit)
- Target Page:  https://www.washington.edu/accesscomputing/AU/before.html

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

Similar to #4326, but this is happening when the menu is selected and menu items are hovered. The icon and menu items are visible when not in the selected/hover states.

**Comment by ferBonnin** [comment]
triaged with @peterdur

**Comment by jlperkins** [comment]
Investigated from a machine running Windows 11.  There are new high contrast modes available in Windows 11, entitled Aquatic, Desert, Dusk, and Night Sky.  The Windows 10 high contrast modes (High Contrast 1, HC2, HC Black, HC White) are no longer available settings in Windows 11.  Each new Windows 11 high contrast theme has color contrast issues, as listed and shown below. The cursor is not visible in the screenshots, but each screenshot was taken with the mouse hovering over the first menu item ("File issue"). 

![aquatic](https://user-images.githubusercontent.com/33770444/139926514-c9db9eb6-d988-4f1d-9304-ccc04085b029.jpg)
Aquatic high contrast theme, with insufficient contrast in the more actions menu icon and the menu items' text when highlighted. 

![desert](https://user-images.githubusercontent.com/33770444/139926515-1f80833d-42b8-4ca2-9862-3562d92112ec.jpg)
Desert high contrast theme, with insufficient contrast in the menu items' text when highlighted. The menu icon here has sufficient contrast. 

![dusk](https://user-images.githubusercontent.com/33770444/139926516-8303c5cc-7226-4efc-bb8d-50dbb8686de4.jpg)
Dusk high contrast theme, with insufficient contrast in the more actions menu icon and the menu items' text when highlighted. 

![night sky](https://user-images.githubusercontent.com/33770444/139926512-4fefa6c1-69f0-4052-ba08-940e1de78b36.jpg)
Night Sky high contrast theme, with insufficient contrast in the more actions menu icon and the menu items' text when highlighted. 

A dev who attempts to work on the original issue here should ideally still be running Windows 10.  There does not appear to be a way to properly apply Windows 10's contrast modes (High Contrast 1, 2, Black, and White) in Windows 11.  Workarounds exist, but do not successfully apply the Windows 10 modes to browsers... instead, you get a mix of modes from Windows 10 and 11 applied to different apps on the screen. See image below, where this mix of modes is shown.  
![image](https://user-images.githubusercontent.com/33770444/139928711-4a9321eb-be02-4c98-a4b9-4312cb583c9e.png)
Image of screen after High Contrast 1 (from Windows 10) was manually enabled on Windows 11.  Teams looks like High Contrast 1, but notepad and edge look like Aquatic (a new Windows 11 theme). 

Because of this, this bug is best addressed by a dev who has not yet updated their machine to Windows 11.

**Comment by katydecorah** [comment]
Providing an update on this bug as result of the FluentUI v8 upgrade (#5244) as the state of this bug has shifted slightly.

## Current state of web

The high contrast issue on the kebab menu was almost completely resolved for web, the **Desert** theme is the only Windows 11 high contrast theme that needs to be addressed.

Theme | Original bug report | Current (post-FluentUI v8 release)
|---|---|---
Aquatic | ![Aquatic high contrast theme, with insufficient contrast in the more actions menu icon and the menu items' text when highlighted. ](https://user-images.githubusercontent.com/33770444/139926514-c9db9eb6-d988-4f1d-9304-ccc04085b029.jpg) | ![Aquatic high contrast theme with sufficient contrast](https://user-images.githubusercontent.com/2180540/157725931-090581ad-8a16-4edf-8993-4b1316265b18.png)
Desert | ![Desert high contrast theme, with insufficient contrast in the menu items' text when highlighted. The menu icon here has sufficient contrast. ](https://user-images.githubusercontent.com/33770444/139926515-1f80833d-42b8-4ca2-9862-3562d92112ec.jpg) | ![Desert high contrast theme with the hover showing still low contrast](https://user-images.githubusercontent.com/2180540/157726065-dd1925a7-da36-40a5-a545-f3a6f2afcb9e.png)
Dusk | ![Dusk high contrast theme, with insufficient contrast in the more actions menu icon and the menu items' text when highlighted. ](https://user-images.githubusercontent.com/33770444/139926516-8303c5cc-7226-4efc-bb8d-50dbb8686de4.jpg) | ![Dusk high contrast theme with sufficient contrast](https://user-images.githubusercontent.com/2180540/157726553-e4f0af9f-85e3-444b-852c-41e41b6022e5.png)
Night sky | ![Night Sky high contrast theme, with insufficient contrast in the more actions menu icon and the menu items' text when highlighted. ](https://user-images.githubusercontent.com/33770444/139926512-4fefa6c1-69f0-4052-ba08-940e1de78b36.jpg) | ![Night sky high contrast theme with sufficient contrast](https://user-images.githubusercontent.com/2180540/157726673-f361b4f6-c9ab-49ea-ad80-167e6f3c5ede.png)


## Current state of unified

The menu items hover state in the kebab menu for unified all have low contrast and need to be addressed, except for Desert where the text has an acceptable ratio but the icon does not.

Theme | Current (post-FluentUI v8 release)
|---|---
Aquatic | ![Insufficient contrast ratio on hovered kebab menu item in Aquatic theme](https://user-images.githubusercontent.com/2180540/157727939-795f3529-cfd5-47ee-9096-a6a87bffd6ab.png)
Desert | ![Insufficient contrast ratio on hovered kebab menu item in desert theme](https://user-images.githubusercontent.com/2180540/157728057-caeeae8d-51ba-4a47-aa6e-3596a693a03a.png)
Dusk | ![Insufficient contrast ratio on hovered kebab menu item in dusk theme](https://user-images.githubusercontent.com/2180540/157728143-d72fb147-a097-419b-b76b-5e08258dd869.png)
Night sky | ![Insufficient contrast ratio on hovered kebab menu item in night sky theme](https://user-images.githubusercontent.com/2180540/157728230-94f232e5-3e3c-41d8-aeda-37bc3894638a.png)


## Summary of bug fix requirements

To close this out, the following will need to be addressed:

- [ ] The contrast ratio of the hover state of kebab menu items in Web using the Desert high contrast theme.
- [ ] The contrast ratio of the hover state of kebab menu items in Unified (against all high contrast themes).
- [ ] If possible, validate hover state of kebab menu and items in Web and Unified with Windows 10 themes as recommended in https://github.com/microsoft/accessibility-insights-web/issues/4616#issuecomment-958083587

**Comment by ferBonnin** [comment]
@lisli1 does this issue ( the more actions button not appearing until hover) repros in production? If yes, then I am ok with filing a different bug and closing this one (as it would not have been introduced by any of these fixes) 🙂

**Comment by lisli1** [comment]
Filed #5614 to track the new issue
