### ISSUE TITLE
FluentUI FocusTrapZone flags aria-hidden-focus rule on Mac but not Windows

### ISSUE THREAD

**Issue by brocktaylor7** [microsoft/accessibility-insights-web#4649]
## Describe the bug

This is an issue to track a very strange behavior that we've observed where a rule is flagged consistently on Mac but not on Windows even though the HTML is seemingly identical on both.

**To Reproduce**

1. Go to [Fluent UI Focus Trap Zone](https://developer.microsoft.com/en-us/fluentui#/controls/web/focustrapzone)
2. Click on any of the "Use Trap Zone" toggles to activate the focus trap zone.
3. Run FastPass on Windows, then run it on Mac.
4. Windows does not flag the aria-hidden-rule for the control. Mac flags two elements with the following HTML:  
`<div aria-hidden="true" tabindex="0" data-is-visible="true" style="pointer-events: none; position: fixed;"></div>`

Note: This is the behavior on both Edge and Chrome.

## Expected behavior

Results should be the same in both Mac and Windows.

## Context (please complete the following information)

- OS Name & Version: Windows 10/Mac OS 11
- AI-Web Version & Environment: AI-Web 2.28.0
- Browser Version: Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)
- Target Page: https://developer.microsoft.com/en-us/fluentui#/controls/web/focustrapzone

**Comment by ferBonnin** [comment]
Per conversation with Peter we should investigate if this happens with pure axe-core as well for next steps. @dbjorge can you help us investigate when possible?

**Comment by dbjorge** [comment]
Sure, I can take a look. For reference, the easiest way to test with pure axe-core is usually to use the F12 developer console to add a script tag to the page pointing to any CDN for npm packages (I like https://unpkg.com). Something like this:

```javascript
const axeScriptElement = document.createElement('script');
axeScriptElement.setAttribute('src', 'https://unpkg.com/axe-core/axe.js'); // or /axe-core@4.3.3/axe.js for a specific version
document.body.appendChild(axeScriptElement);
const axeResults = await axe.run();
axeResults.violations; // or whatever else you want to see
```

I verified the original report, ie, that the issue repros on mac but not windows in both pure axe-core as well as Accessibility Insights. On closer inspection of the windows results, the rule in question shows up as "incomplete". This generally indicates that one of the checks used by the rule was not able to report a conclusive result. I looked a little further into why that might be as follows:

* I used the mac scan results to identify the specific problem element in question
* I went back to the windows machine and used the "inspect" F12 tool on the same element to give it an `id="problem"` attribute, to make it easier to find during debugging
* I opened the F12 "Sources" view and searched for `aria-hidden-focus`, and found the definition of the different checks it uses (`focusable-modal-open', 'focusable-disabled', 'focusable-not-tabbable'`)
* I searched for each of those and set a breakpoint inside of each check implementation
* I reran axe with a tigher scope: `await axe.run('#problem', { runOnly: 'aria-hidden-focus' })`
* I stepped through each of the checks as they ran to identify what path was causing one to return an incomplete result

This showed that the incomplete was happening because the `focusable-modal-open` check detected that a modal dialog was open on the page in Windows, but not on Mac. The `aria-hidden-focus` rule is intended to give incomplete results when a modal dialog is open anywhere else on the page.

On Windows, the page in question includes a banner advertisement for the Bing Wallpaper app (see below screenshot), which axe-core treats as a modal because it includes an element which uses `role="dialog"`. If you dismiss the advertisement, the `aria-hidden-focus` violation will show up on Windows. Note that dismissing the advertisement is "sticky", so you may need to open the page in an in-private window to see the advertisement if you've dismissed it previously.

![screenshot of page on windows with Bing Wallpaper banner ad highlighted](https://user-images.githubusercontent.com/376284/133334867-c3e82296-a025-4205-b619-3b30c997d683.png)

On Mac, the Bing Wallpaper advertisement never appears, so the `aria-hidden-focus` check works without any intermediate user interaction.

Technically speaking, the internal `axe-core` terminology is a little inaccurate; their `isModalOpen` check assumes that any `<dialog>` element or any element with `role=dialog` is modal (in addition to checking `aria-modal`, but this isn't really accurate; dialogs are allowed to be modal or non-modal, and ideally a non-modal dialog like this one shouldn't trip the modal-specific logic. The discussion from https://github.com/dequelabs/axe-core/issues/1482 and the comments added in https://github.com/dequelabs/axe-core/pull/1995/files suggest that it was an intentional decision to attempt to err on the side of treating "probably a modal is open but we can't say for sure" as being open for the purposes of checks like this one, which makes sense to me from the standpoint of wanting to reduce false positives.

@ferBonnin / @juchampa , in terms of followup on our end, I think the followup that this suggests is really that our Needs Review section should ideally include cases like this where axe-core thinks the analysis is incomplete, rather than allowing the incomplete results to be silently ignored. I think axe-core is doing the right thing here to say "this rule can't be evaluated while a modal is open and we think a modal might be open but can't be sure, so we're marking the result as incomplete."

**Comment by ferBonnin** [comment]
per conversation with Peter,  and per earlier investigations since we don't want to show incomplete in _Needs review_ (possibility for lots of noise) and the fact that users would still see different results (one in _automated checks_, the other in _needs review_) because the page is different in each platform, marking as out of scope
