### ISSUE TITLE
Tool is ignoring tabIndex=-1

### ISSUE THREAD

**Issue by pedroafsouza** [microsoft/accessibility-insights-web#5222]
The original bug has been described on this https://github.com/microsoft/fluentui/issues/21904. As explained for one of the deveopers, it looks like this is an issue on the tool side:

![image](https://user-images.githubusercontent.com/957088/156346466-da4b2a53-be98-4699-86ba-052372fbfdb0.png)

**Comment by shanisebarona** [comment]
Hi @pedroafsouza, here is a helpful explanation regarding the nested-interactive rule failing with `tabIndex = -1`: https://github.com/dequelabs/axe-core/issues/3227#issuecomment-949684411

We will be working to update the rules engine version so that we can bring the improved error message into the tool.
