### ISSUE TITLE
[Unified] Broken link in telemetry pop-up dialog

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-web#5374]
## Describe the bug

The "help the community" link (https://accessibilityinsights.io/docs/telemetry) in the telemetry pop-up dialog is broken. It should instead point to https://accessibilityinsights.io/docs/android/reference/telemetry/

**To Reproduce**

1. Start with a fresh install of Accessibility Insights for Android
2. Launch the app
3. Select the "help the community" link in the "We need your help" telemetry dialog
4. See that it opens https://accessibilityinsights.io/docs/telemetry in a browser, which contains "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

## Expected behavior

The link should go to https://accessibilityinsights.io/docs/android/reference/telemetry/

## Context (please complete the following information)

- OS Name & Version:  Windows Version 10.0.22000 Build 22000
- AI-Web Version & Environment:  Insider 2022.411.12
- Browser Version:  Edge Version 100.0.1185.39 (Official build) (64-bit)
- Target Page:  n/a

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

**Comment by peterdur** [comment]
I think this link should actually go to https://accessibilityinsights.io/docs/general/telemetry/ (rather than the Android-specific page suggested above). The redirects added in https://github.com/microsoft/accessibility-insights-docs/pull/1135/files#diff-d768796153b4cb52bcce46cffce7d2a46da96c912bd72d9381768f78b3b67592R16 almost do this, but they assume a slash at the end of the URL. Making the slash optional should fix this and similar links.

**Comment by lisli1** [comment]
Verified the link is now fixed in Accessibility Insights for Android Insider 2022.411.12
