### ISSUE TITLE
Allow disabling notifications

### ISSUE THREAD

**Issue by traisjames** [microsoft/accessibility-insights-web#5917]
Simple thing.  I just want to be able to turn off notifications when I am doing a check.  I know I am doing checks and am watching for results.  I don't need to be told when they are found.

**Comment by ferBonnin** [comment]
Thanks for the feature request @traisjames!
Could you please let us know which OS and browser you are using?


We triaged this with the team and we will be investigating:
* Is there a way to turn off notifications for a single extension via OS or browser?
* Are there other things where we rely on the OS notifications to notify users?
Leaving this as ready for triage to continue the conversation next week

**Comment by traisjames** [comment]
Google Chrome Version 104.0.5112.79 running on OS X 10.15.7

**Comment by pownkel** [comment]
@ferBonnin After investigating, Chrome doesn't seem to have a way to block notifications for an extension, and the functionality for blocking notifications from a site doesn't work with extension URLs.

The places where we use notifications are:
- After running an Automated Checks or Needs Review scan (from fastpass or ad hoc visualizers)
- Whenever the tab stops visualizer is enabled
- When enabling any visualizer with a keyboard shortcut
- When trying to enable a visualizer via keyboard shortcut on a URL that is not scannable (either if it's a file URL and the extension hasn't been granted permissions, or if the extension doesn't have access for some other reason)

All of these cases go through [NotificationCreator](https://github.com/microsoft/accessibility-insights-web/blob/main/src/common/notification-creator.ts), so adding a global switch wouldn't be complicated, but I'm not sure we'd want to disable all of those cases (particularly the unscannable URL messages, since we otherwise don't communicate why the scan didn't run)

**Comment by traisjames** [comment]
What about doing switches for each reason, because if its something automated yea an alert is nice, but if I manually run a check and am sitting on the page I am checking, I am ok without the notification.

**Comment by ferBonnin** [comment]
thanks for the investigation @pownkel! We are marking this as await community interest to correctly prioritize

**Comment by dbjorge** [comment]
@ferBonnin FYI, we received a customer request in the "Support" section of [our Chrome Web Store listing](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en) yesterday which is a +1 for this feature:

> Allow turning off notifications
>
> This extension has too many notifications. Please let us toggle it off.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
