### ISSUE TITLE
english a/an in error text

### ISSUE THREAD

**Issue by Bram-diederik** [microsoft/accessibility-insights-web#6122]
My Dutch translation picked up some new tests that i believe are in error.

I did a google search and i state that I'm correct https://www.a-or-an.com/a_an/undefined

test messages:
"A undefined element must be coded correctly as a data table or a layout table"
"The headers attribute of a undefined element must reference the correct undefined element(s)"

**Comment by madalynrose** [comment]
Thank you for letting us know about this issue, @Bram-diederik! Could you point us to where you are seeing these messages?

**Comment by Bram-diederik** [comment]
Its a test case string somewhere in a html or json result export. My translation dictionary picked them up when i added the json format into my parser. 

Any html or json result export contains the error and can be found there.

**Comment by madalynrose** [comment]
Thank you for finding this issue @Bram-diederik! It turned out to be a bug in the JSON export process where we parse the JSX description for requirements. `undefined` was being inserted into the final description instead of the element name (e.g. `header`, or `td`) in some cases and your attention to grammar highlighted this issue though it is present in more than those two places. A fix has been merged into main and will go out in the next release of the web extension!
