### ISSUE TITLE
Color-contrast gives inconsistent results

### ISSUE THREAD

**Issue by Sharon-Klebanov** [microsoft/accessibility-insights-web#6443]
## Describe the bug
I have two elements with same color and color background but I get different results for both of the elements
Color background  - rgba(0, 0, 0, .05)
Color - rgba(0, 0, 0, .22)

I am not sure if this is false positive or not.

**To Reproduce**

1. Go to https://www.videoindexer.ai/
2. Click on Upload
3. Upload a video with default options
4. Wait for uploading and indexing processes to finish
5. Click on video item options (vertical three dots button)
6. Click on re-index option
7. In the re index popup run accessibility fast pass

## Expected behavior
Consistent result for both elements with same color contrast

## Screenshots
First input doesn't get any error 
Second get an error
![image](https://user-images.githubusercontent.com/13219802/219955432-cacbb9e7-e7ac-4635-a3a4-10722e60f741.png)

## Are you willing to submit a PR?
Yes

## Did you search for similar existing issues?
Yes

**Comment by dbjorge** [comment]
Hi @Sharon-Klebanov ,

This is expected behavior. The discrepancy is occurring because:

* The `color-contrast` rule is not applicable to controls in a disabled state (like the "Video name" input text box you've labelled "1" in your screenshot) - this is why there is no error on the "Video name" control.
* However, the disabled Privacy dropdown for some reason repeats the word "Private" twice:
  * Once as the `value` of the `input` element with `role="combobox"` - this is correct, and Accessibility Insights correctly recognizes this as a disabled control and doesn't report a `color-contrast` issue here
  * A second time as a descendant of the `div` element with the `ui-dropdown-label-container` class. This is not correct, and will confuse accessibility technologies like screen readers. If you use the browser's F12 dev tools to examine the accessibility tree around this combobox, you'll find that this repeated "Private" text appears in the accessibility tree as a sibling of the combobox (not as part of the combobox), and if you test out this control in a screen reader (such as NVDA), you'll hear that the screen reader announces the word "Private" twice here (once as part of announcing the disabled combobox, and then a second time for the repeated text).

The error is being reported on the second instance of the word "Private" (the one that isn't technically part of the combobox). The correct fix here would be to fix the combobox component such that this extra copy of the selected contents is not repeated in the accessibility tree. Ideally, you'd want to do this by not having it in the DOM at all.
