### ISSUE TITLE
False positive for automated check: <li> elements must be contained in a <ul> or <ol>

### ISSUE THREAD

**Issue by ambrosew** [microsoft/accessibility-insights-web#665]
## Describe the bug

Possible false positive for automated check: ```<li> elements must be contained in a <ul> or <ol>```

1. Go to https://codepen.io/ambrosew/pen/YbqvBX
2. Run automated check.
3. ```<li>``` are flagged as not contained in a ```<ul>```.

## Expected behavior

Expect no such error because ```<li>``` are contained in a ```<ul>``` with role="link"

## Screenshots

![image](https://user-images.githubusercontent.com/3521748/57541551-2176ad80-7304-11e9-8043-53e0c93e95ab.png)

## Extension (please complete the following information)

OS: Windows 10 Version 10.0.17763.437
Chrome version 74.0.3729.131
This accessibility issue was found using Accessibility Insights for Web 2019.5.10.11 (axe-core 3.2.2)

## Are you willing to submit a PR?
Yes

## Did you search for similar existing issues?
Yes

**Comment by ferBonnin** [comment]
Hi @ambrosew this is not a false positive. You are overwriting the role list with role **link**: `<ul aria-labelledby="label1" role="link">` .  You can check this if you go to the accessibility tab when inspecting the elements:
![a screenshot of the accessibility tree](https://user-images.githubusercontent.com/9062104/57544054-0e1b1080-730b-11e9-97f7-9892438e8829.png)

The rule "listitem" makes sure that all the elements with role="listitem" are directly contained inside an element with role="list", otherwise, a screen reader will not notify the users that there is a list with N elements.

If you remove role = "link" the automated checks won't flag this anymore.

**Comment by ambrosew** [comment]
Thanks for the feedback!
