### ISSUE TITLE
FastPass Does Not Associate Labels with Custom Elements

### ISSUE THREAD

**Issue by break-stuff** [microsoft/accessibility-insights-web#6798]
## Describe the bug

When using the [ElementInternals API](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals), form-associated custom elements are showing a missing label error when a label is associated with it.

**To Reproduce**

1. Go to 'https://cdpn.io/break-stuff/fullpage/qBQPGVb?nocache=true&view=fullpage'
2. Run Accessibility Insights FastPass

## CodePen repro example

https://codepen.io/break-stuff/pen/qBQPGVb?editors=1011

## Expected behavior

It should correctly associate the label with the component.

## Context (please complete the following information)

- OS Name & Version: macOS Ventura 13.4.1 
- AI-Web Version & Environment: 2.38.1
- Browser Version: 114.0.5735.198
- Target Page: https://cdpn.io/break-stuff/fullpage/qBQPGVb?nocache=true&view=fullpage

## Are you willing to submit a PR?

No

## Did you search for similar existing issues?

Yes

**Comment by DaveTryon** [comment]
Looking at this, I suspect that the problem isn't the custom control, but that the custom control is a node _inside_ a shadow DOM, while the label is _outside_ the shadow DOM, even though the shadow DOM is open. Several posts online (including [this one](https://github.com/dequelabs/axe-core/issues/4044#issuecomment-1567999212) from WilcoFiers of the axe team) suggest that it's intentional behavior for an IDREF property to cross a shadow DOM boundary. That's how shadow DOM provides isolation between the contents of multiple (and potentially conflicting) elements within shadow DOMs on the same page.

**Comment by DaveTryon** [comment]
We believe this is by design for the reasons listed above. Please reopen it if you find formal documentation that suggests that the `label` tag is intended to be able to apply to items within a shadow root.

**Comment by break-stuff** [comment]
Creating form-associated custom elements using the `ElementInternals` API allows custom elements to behave as input elements and be associated with forms and labels.

https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals

**Comment by break-stuff** [comment]
For more information, this ticket was elevated to axe-core.

https://github.com/dequelabs/axe-core/issues/4085
