### ISSUE TITLE
Decorative elements with a CSS background-image are reported as Meaningful when a nested element has an aria-label

### ISSUE THREAD

**Issue by mmafe** [microsoft/accessibility-insights-web#696]
## Describe the bug

Decorative elements with a CSS background-image are reported as "Meaningful" when there is a nested element (in this case a `<nav>`) with an aria-label inside of the decorative container element.

Tool guidance specifically says:
 
1. Examine each image to verify that its coded function is correct.
   - An image should be coded as meaningful if it conveys information that isn't available through other page content.
   - An image should be coded as decorative if it could be removed from the page with no impact on meaning or function.
2. Record your results:
   - Select Fail for any instances that do not meet the requirement.
   - Otherwise, select Pass. Or, after you have marked all failures, select Pass unmarked instances.

Based on the tool guidance, these elements would be marked as "Fail"s even though I believe they are Passes.

## To Reproduce
HTML structure is as follows:

```
<div id="parent-element">
   <div class="container"> 
     <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top" aria-label="Label for the nested element">
          ...
        </nav>
   </div>
</div>
```
CSS code is as follows:
```
 #parent-element {
    color: #FEFEFE;
    background: url(https://images.unsplash.com/photo-1547499417-61a435d27cb3?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&h=200&fit=crop&ixid=eyJhcHBfaWQiOjF9);
    background-repeat: repeat-x;
}
```

**Codepen Reproduction Steps**

1. Go to this [codepen](https://codepen.io/anon/pen/LoeXoV). Alternatively, create an element with a CSS background image (decorative). Inside the element, add a nested element with an aria-label
2. Run an assessment on the page (or run an assessment on this )
3. Open the Images / Image function section
4. You will then see the following for the element with the CSS background image

```
Image type: CSS background-image
Coded as: Meaningful
Accessible name: Label for the nested element
```
## Expected behavior

Since the element with the CSS background-image is decorative and is coded using a CSS background-image, I would have expected to see this scenario coded as "Decorative".

Is this a false positive?

## Are you willing to submit a PR?
Not sure how to fix.

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights): Yes

**Comment by mmafe** [comment]
Relating to this, when the CSS background-image is coded as Meaningful, any instances of it will also show up under the Images/ Text alternative section as a meaningful image that requires a text alternative. 

The guidance of this second section says...

```
1. Examine each image in the Instances list to verify that its text alternative serves the equivalent purpose.
   - A simple image should have an accessible name that serves the equivalent purpose. Special cases:
      - An image of text should have an accessible name that exactly matches the text within the image.
      - A CAPTCHA image should have an accessible name that communicates the purpose of the image, but not its content. (A CAPTCHA is a test to differentiate a human from a computer.)
   - A complex image (such as a graph) should have both
      - An accessible name that communicates the purpose of the image, and
      - An accessible description that communicates the content of the image.
2. Record your results:
   - Select Fail for any instances that do not meet the requirement.
   - Otherwise, select Pass. Or, after you have marked all failures, select Pass unmarked instances.
```

Based on the tool guidance, these instances (under Images/Text Alternative) would also be marked as "Fail"s even though I believe they are Passes.

**Comment by LiLoDavis** [comment]
To avoid both false positives and false negatives related to CSS images with meaningful content, we'll need to make the following changes. 
Note that test steps starting with lower case Roman numerals (i, ii, iii) should be indented relative to test steps starting with lower case letters (a, b). (I couldn't get the formatting to display properly.)
### Automated checks
The **image-alt** rule will fail for a CSS background image with role="img" but no accessible name.
### Images > Image function
#### Instances
1. Show all/only images that are coded as meaningful or decorative. Do not show images that has no code identifying it as meaningful or decorative.
2. For CSS background images, svg images, or icon fonts to be coded as meaningful, they must have both `role="img"` and an accessible name.
3. Show whether `role="img"` is present. Here are some examples for CSS images:

Image type: CSS background-image
Coded as: decorative
ARIA role: (no value)
Accessible name: (no value)

Image type: CSS background-image
Coded as: decorative
ARIA role: (no value)
Accessible name: Robot smiling at a dog

Image type: CSS background-image
Coded as: (no value)
ARIA role: img
Accessible name: (no value)

Image type: CSS background-image
Coded as: meaningful
ARIA role: img
Accessible name: Robot smiling at a dog
#### How to test
For this requirement, Accessibility Insights for Web highlights images that are coded as meaningful or decorative. 
_Notes: (1) If an image has no code to identify it as meaningful or decorative, it will not be shown here; instead it will fail an automated check. (2) Assistive technologies will ignore any image coded as decorative, even if it has an accessible name. (3) If no matching/failing instances are found, this requirement will automatically be marked as **Pass**._
1.	Examine each image to verify that its coded function is correct:
a.	An image should be coded as _meaningful_ if it conveys information that isn't available through other page content.
b.	An image should be coded as _decorative_ if it could be removed from the page with no impact on meaning or function.
2.	Record your results:
a.	Select **Fail** for any instances that do not meet the requirement.
b.	Otherwise, select **Pass**. Or, after you have marked all failures, select **Pass unmarked instances**.
#### How to fix
1.	Determine the function of the image:
•	If the image conveys information that isn't available through other page content, it's meaningful.
•	If the image could be removed from the page with no impact on meaning for function, it's decorative.
1.	If the image is meaningful:
•	Make sure it has a descriptive accessible name using a _non-empty_ `alt`, `aria-label`, `aria-labelledby`, or `title` attribute. (Only `<img>`, `<input>`, and `<area>` elements can have `alt` attributes.)
•	If it's an icon font, `<svg>` image, or CSS background image, also add `role="img"`.
•	If it's a CSS background image, also add a text element that conveys the image's information and is visible when CSS is turned off.
2.	If the image is decorative:
•	And it's an `<img>`, `<input>`, or `<area>` element, add an empty `alt` attribute (`alt` or `alt=""`).
•	And it's an icon font or `<svg>` image, add `role="img"` and `aria-hidden="true"`.
•	And it's a CSS background image, no additional markup is needed.
### Images > Text alternative
#### Instances
1. Show all/only images that are coded as meaningful.
2. For CSS background images, svg images, or icon fonts to be coded as meaningful, they must have both `role="img"` and an accessible name.
#### How to test
For this requirement, Accessibility Insights for Web highlights images that are coded as meaningful.
_Notes: (1) This procedure may require use of the [Web Developer](https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm) browser extension. (2) If no matching/failing instances are found, this requirement will automatically be marked as **Pass**._ 
1. Examine each image in the **Instances** list to verify that its text alternative serves the equivalent purpose.
  a. A _simple_ image should have an accessible name that serves the equivalent purpose. Special cases:
     i. An image of text should have an accessible name that exactly matches the text within the image.
    ii. A CAPTCHA image should have an accessible name that communicates the purpose of the image, but not its content. (A CAPTCHA is a test to differentiate a human from a computer.)
  b. A _complex_ image (such as a graph) should have both
    i. An accessible name that communicates the purpose of the image, and
   ii. An accessible description that communicates the content of the image.
2. If a CSS background image is coded as meaningful:
  a. Use the Web Developer browser extension (**CSS** > **Disable All Styles**) to turn off CSS.
  b. Verify that the information conveyed by the image is visible when CSS is turned off.
3. Record your results:
  a. Select **Fail** for any instances that do not meet the requirement.
  b. Otherwise, select **Pass**. Or, after you have marked all failures, select **Pass unmarked instances**.
### Images > Images of text
#### Instances
1. Show all/only images that are coded as meaningful.
2. For CSS background images, svg images, or icon fonts to be coded as meaningful, they must have both `role="img"` and an accessible name.

**Comment by LiLoDavis** [comment]
I'll crate a separate issue for the automated check.

**Comment by ferBonnin** [comment]
For summary, for whomever picks this up:

- Requires change of what we show to the user (include aria-role). 
- 1.b is optional (we don't do this in other tests) 
- and there is also a text change

**Comment by karanbirsingh** [comment]
Looked at this and I think we need the `role-img-alt` rule slated for Axe's upcoming milestone. We consume axe-core 3.2.2 and the rule is planned for 3.3.
- milestone: https://github.com/dequelabs/axe-core/milestone/8
- issue: https://github.com/dequelabs/axe-core/issues/1192
- axe PR: https://github.com/dequelabs/axe-core/pull/1586

**Comment by karanbirsingh** [comment]
axe-core 3.3 is out, we are likely able to pick this up now - needs investigation to double-check

**Comment by ferBonnin** [comment]
Not ready for work, will take this as part of the update axe-core feature.

**Comment by ferBonnin** [comment]
marking as ready for triage to review again

**Comment by ferBonnin** [comment]
as a summary again, needs to:

- do a text change on the how to test information
- change what images we show to users (1a) 
- show aria-role as part of the instance values (2)

**Comment by lisli1** [comment]
Also looked into this; work-in-progress on [this branch](https://github.com/microsoft/accessibility-insights-web/compare/master...lisli1:lisli1/bug-decorative-elements-with-background-reported-as-meaningful), which should have all the requested text changes and aria-role shown as part of instance values (2). 

Still needs:
- change what images are shown to users for Text Alternative and Images of Text (1a). Note: it seems that both Text Alternative and Images of Text use the textAlternativeConfiguration with rule id 'accessible-image'.

**Comment by ferBonnin** [comment]
Hi @mmafe we have fixed this issue and the new version is available in our  [Canary  extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/hbcplehnakffdldhldncjlnbpfgogbem).

Please let us know what you think!

**Comment by mmafe** [comment]
@ferBonnin Hey guys, thank you so much for looking into this issue! Unfortunately, with all that's going on right now, it's unlikely I'll be able to review the new version in a timely fashion. If you are confident the issue is fixed, please feel free to close the issue. Thank you!

**Comment by ferBonnin** [comment]
Hi @mmafe no worries, we understand! 
Thank you!
