### ISSUE TITLE
Allow `aria-selected` for `role=gridcell`

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/accessibility-insights-web#7498]
## Describe the bug

I am using a grid with gridcells and the primary mechanism for deciding if a row was selected is via the gridcell.
According to this reference (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected), aria-selected is a compatible attribute with the gridcell roll.

**To Reproduce**

1. Go to the stackblitz link provided.
2. Open the preview in a different tab.
3. Run FastPass in the Accessibility Insights web browser extension.

## CodePen repro example

https://stackblitz.com/run?file=src%2Fexample.tsx

## Expected behavior

No error from FastPass.

## Screenshots

![Image](https://github.com/user-attachments/assets/04949268-342f-460a-838c-2df8f8ad9291)

## Context (please complete the following information)

System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 42.17 GB / 63.95 GB
  Browsers:
    Edge: Chromium (131.0.2903.48)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @fluentui/react: ^8.112.8 => 8.115.6
    @fluentui/react-components: 9.38.0 => 9.38.0
    @fluentui/react-hooks: ^8.6.33 => 8.6.36
    @fluentui/react-icons: ^2.0.221 => 2.0.227
    @fluentui/react-portal-compat: ^9.0.110 => 9.0.128
    @types/react: ~17.0.2 => 17.0.75
    @types/react-dom: ~17.0.2 => 17.0.25
    react: ~17.0.2 => 17.0.2
    react-dom: ~17.0.2 => 17.0.2

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

**Comment by v-viyada** [comment]
Hi @aubreyquinn, as per latest document for [aria-checked](https://www.w3.org/TR/wai-aria/#aria-checked), it is not valid for `role=gridcell`. It looks to be issue with fluent ui DataGrid component. Please refer open issue https://github.com/microsoft/fluentui/issues/31073

**Comment by smhigley** [comment]
Hi all! The reason we use `aria-checked` instead of `aria-selected` is because our multiselect grid can result in a mixed-state checkbox in the header cell. Only `aria-checked` supports that state; `aria-selected` is not sufficient. Since `aria-checked` does have some practical support and actually provides a better and more informed user experience than `aria-selected` in practice, we use it because the priority of constituencies puts end users above authors, browser devs, and spec purity 😅.

There is currently an issue open on the ARIA spec to add `aria-checked` as an allowed prop on `role=gridcell`, and it has general consensus from the working group to proceed. The ball is actually in my court to push it forward, it just got kinda deprioritized because of other efforts which is on me 😅.

Would Accessibility Insights be at all interested in removing the error for this attribute in the meantime, since it does no harm? I'd understand either way, TBH.

**Comment by joestegman425** [comment]
Hi Sarah,

That context is helpful and hopefully you can get the ARIA spec updated.

Related to the error message, Accessibility Insights for Web uses [Deque's axe-core](https://github.com/dequelabs/axe-core) as the detection engine and the error in question comes from axe-core. As such, similar to your ARIA work, you will need also work with Deque to have them remove the error. Note that the axe-core implementation is in a public repository.

Joe
