### ISSUE TITLE
programmatic api for extension

### ISSUE THREAD

**Issue by zzo** [microsoft/accessibility-insights-web#787]
## Is your feature request related to a problem? Please describe.
I would like to kick off an accessibility run programmatically from within my webpage. I am creating a web UI that wants to programmatically launch MS AI against a given URL (see https://developer.chrome.com/apps/messaging#external-webpage)

## Describe the desired outcome
Ideally would like to postMessage to the extension with a URL and an opaque token and whether to run FastPass or Manual accessibility checks. AI will then run either and when the user clicks 'Export Report' the report will be postMessage'd back to my UI (ideally this report would be in JSON not HTML but don't want to confuse/add any extra work initially!)

## Describe alternatives you've considered
I can drive the extension using puppeteer but that requires users to download local code (to spawn the browser with the URL and MS AI pointing back to it).
I can also create another extension to drive the process but that's clunky plus requires Chrome to be started with additional, non-standard command line arguments (--silent-debugger-extension-api and --extensions-on-chrome-urls)
The cleanest solution is to update MS AI itself to have an API that can be driven by any page.

## Additional context
THANKS - I can look into creating a PR for this if this is something you'd accept

**Comment by dbjorge** [comment]
Hi Mark,

Thanks for writing up this request! Typically, we recommend that folks looking to automatically/programatically run accessibility scans use [axe-core](https://github.com/dequelabs/axe-core) (the accessibility scanning engine Accessibility Insights uses under the hood for all of its automated checks) directly, which already provides JSON-formatted scan results and has [many integration](https://www.deque.com/axe/axe-for-web/integrations/) libraries to help you run it from a variety of different languages and test frameworks, and [we have published samples](https://github.com/microsoft/axe-pipelines-samples) of how to integrate it in Azure Pipelines CI builds.

Does axe-core sound like what you're looking for? If not, can you help us understand more about your motivation for wanting to automate at the Accessibility Insights level specifically, rather than at the scanning engine level?

**Comment by zzo** [comment]
thanks for the response!  We already do use axe-core to run automated browser testing - I'm interested in incorporating your manual tests into our a11y testing workflow tool - that's where things are much more interesting.
From our browser-based a11y testing toolkit/dashboard we'd like to launch MS AI in 'manual testing mode' against a given URL and when the tester is done doing all of the relevant manual tests, then suck the results back into our tool to show alongside of the axe results providing a dashboard of release readiness ( from an a11y point of view).
So we already collect axe results against their configured set of URLs and would like to incorporate manual testing (powered by AI) into our suite.
What do you think?? thanks!!!  Mark

**Comment by ferBonnin** [comment]
Hi @zzo thanks your interest in the tool and the feature request!
We have received a similar ask #653 and we will add both to our needs investigation backlog. We will update here when we know more and we will keep checking for upvotes/reactions from the community on this request

**Comment by adbajaj** [comment]
This would be very helpful for my team as well! Would be interested to know ball park timings on when this is coming.
Thanks,
Aditya

**Comment by mohanraj-r** [comment]
I use axe-core and have been thinking about something similar as well!

**Comment by ferBonnin** [comment]
based on conversation when revisiting this feature request, we have created a way to export an Assessment report as JSON and at this moment we believe the implications of creating an API are out of the scope for the project
