### ISSUE TITLE
new report summary is not consistent with current

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-web#812]
## Describe the bug
the summary in new report has: failed, passed, incomplete.
In Assessment report, the order is pass, incomplete, fail.

**To Reproduce**

1. Go to any website
2. run automated checks
3. download report and add a comment with line breaks and spaces
4. open report

## Screenshots

![FastPass report](https://user-images.githubusercontent.com/9062104/59628613-ebdc9580-90f5-11e9-8bca-c1c2fc29af35.png)

![Assessment report](https://user-images.githubusercontent.com/9062104/59628658-06af0a00-90f6-11e9-982f-1ccc46618902.png)

## Extension (please complete the following information)

- OS: [e.g. Windows/Mac] Windows
- Version [e.g. 1.140.1] 2.5.1
- Browser Version [e.g Chrome 71.0] 74
- Target Page [e.g www.bing.com] any

## Are you willing to submit a PR?

If asked, will you be willing to submit a PR to fix this bug? No

## Did you search for similar existing issues?

Did you search for similar issues in our github issues or on [stackoverflow](https://stackoverflow.com/questions/tagged/accessibility-insights) Yes

## Additional context

Found during validation

**Comment by ferBonnin** [comment]
@cheade thoughts on this?

**Comment by cheade** [comment]
Hi! We’ve discussed this before.

I designed them differently as they are used for two different purposes.

In the FastPass report, users are primarily looking for their errors to fix, and this can become a backlog of sorts

In the Assessment report, users want to see how close they are to passing and how accessible their site is, which is why Passing is listed first.

If this is not the case, then we should align with what users want to see first in their reports 👍🏻

**Comment by ferBonnin** [comment]
@cheade I agree design of both reports should be different/its ok its different.

Thinking more about this, if we show in the summary A, B and C, shouldnt the details section below be A details, B details, C details too? (we do that in fastpass, not in assessment)

**Comment by ferBonnin** [comment]
per conversation, nothing to fix here.
