### ISSUE TITLE
Extension ignores tab stops inside web-components.

### ISSUE THREAD

**Issue by GeorgeTailor** [microsoft/accessibility-insights-web#950]
## Describe the bug

With enabled `tab stops` tracking, it does not shows actual tab stops inside web-components.

**To Reproduce**

1. Go to https://zooplus.github.io/zoo-web-components/
2. Enable extension.
3. Go to `Ad hoc tools`
4. Enable `Tab stops`
5. Start pressing `Tab` button.
6. Observe that actual tab stops in web-components are not tracked by the extension.

## Expected behavior

Extension should handle tab stops which are located inside web components.

## Extension (please complete the following information)

- OS: Mac
- Version 2.6.0
- Browser Version Chrome 75.0
- Target Page https://zooplus.github.io/zoo-web-components/

**Comment by smoralesd** [comment]
@GeorgeTailor thanks for your interest on accessibility insights web.

We need to investigate this issue before having a proper response.

Preliminary, this may be due to the fact the use of web components, which uses shadow dom but we would like to have more info in order to properly find the root cause and a possible solution.

Is it possible that you add a code pen repro example to this issue?

**Comment by Malvoz** [comment]
I'm experiencing the same issue with tab stops in https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/examples/create-map.html#mapkit-js. Can you reproduce?
